name: Download dataset

on:
  workflow_dispatch:

env:
  IMAGE_NAME: polevanovairina/visloc-apr

jobs:
  perform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push image to registry
        uses: whoan/docker-build-with-cache-action@fix-json-extra-args
        with:
          dockerfile: "download.Dockerfile"
          username: "polevanovairina"
          password: "lubluvovu"
          image_name: "polevanovairina/visloc-apr"
          image_tag: "with_dataset"

