name: Test

on:
  workflow_dispatch:

env:
  IMAGE_NAME: polevanovairina/visloc-apr

jobs:
  perform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get image tag
        run: |
          IMAGE_ID=$IMAGE_NAME
          VERSION="tested" 
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
      - name: Test
        run: ./test.sh

      - name: Push image to registry
        uses: whoan/docker-build-with-cache-action@fix-json-extra-args
        with:
          username: "polevanovairina"
          password: "lubluvovu"
          image_name: "${{ env.IMAGE_ID }}"
          image_tag: "${{ env.IMAGE_TAG }}"

